// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniProject_2;

#nullable disable

namespace MiniProject_2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221011112614_AddingThreeOffices")]
    partial class AddingThreeOffices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MiniProject_2.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("ConvertPriceFromUSD")
                        .HasColumnType("float");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConvertPriceFromUSD = 0.84999999999999998,
                            Country = "England",
                            Currency = "GBP"
                        },
                        new
                        {
                            Id = 2,
                            ConvertPriceFromUSD = 10.42,
                            Country = "Sweden",
                            Currency = "SEK"
                        },
                        new
                        {
                            Id = 3,
                            ConvertPriceFromUSD = 1.0,
                            Country = "USA",
                            Currency = "USD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
